// <auto-generated>
//   Сгенерировано tools/gen-patch229.py из живой схемы слоя (telegram_api.tl).
//   Не править руками: при новой дыре в разборе — перегенерировать.
//   Базы: 
// </auto-generated>

using System;

namespace TL
{
	/// <summary>Слой 229: inputPeerPhotoFileLocationLegacy </summary>
	[TLDef(0x27D69997)]
	public sealed partial class InputPeerPhotoFileLocationLegacy : InputFileLocationBase
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public InputPeer peer;
		public long volume_id;
		public int local_id;

		[Flags] public enum Flags : uint
		{
			big = 0x1,
		}
	}

	/// <summary>Слой 229: inputStickerSetThumbLegacy </summary>
	[TLDef(0x0DBAEAE9)]
	public sealed partial class InputStickerSetThumbLegacy : InputFileLocationBase
	{
		public InputStickerSet stickerset;
		public long volume_id;
		public int local_id;
	}

	/// <summary>Слой 229: messageActionStarGiftUnique </summary>
	[TLDef(0x7E1C1187)]
	public sealed partial class MessageActionStarGiftUniqueV229 : MessageAction
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public StarGift gift;
		[IfFlag(3)] public int can_export_at;
		[IfFlag(4)] public long transfer_stars;
		[IfFlag(6)] public Peer from_id;
		[IfFlag(7)] public Peer peer;
		[IfFlag(7)] public long saved_id;
		[IfFlag(8)] public StarsAmount resale_amount;
		[IfFlag(9)] public int can_transfer_at;
		[IfFlag(10)] public int can_resell_at;
		[IfFlag(12)] public long drop_original_details_stars;
		[IfFlag(15)] public int can_craft_at;
		[IfFlag(18)] public TextWithEntities message;

		[Flags] public enum Flags : uint
		{
			upgrade = 0x1,
			transferred = 0x2,
			saved = 0x4,
			refunded = 0x20,
			prepaid_upgrade = 0x800,
			assigned = 0x2000,
			from_offer = 0x4000,
			craft = 0x10000,
			name_hidden = 0x20000,
			has_can_export_at = 0x8,
			has_transfer_stars = 0x10,
			has_from_id = 0x40,
			has_peer = 0x80,
			has_saved_id = 0x80,
			has_resale_amount = 0x100,
			has_can_transfer_at = 0x200,
			has_can_resell_at = 0x400,
			has_drop_original_details_stars = 0x1000,
			has_can_craft_at = 0x8000,
			has_message = 0x40000,
		}
	}

	/// <summary>Слой 229: messageActionChatJoinedViaCommunity </summary>
	[TLDef(0x4A8BFE80)]
	public sealed partial class MessageActionChatJoinedViaCommunity : MessageAction
	{
		public long community_id;
	}

	/// <summary>Слой 229: sendMessageTextDraftAction </summary>
	[TLDef(0x3630B85A)]
	public sealed partial class SendMessageTextDraftActionV229 : SendMessageAction
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public long random_id;
		public TextWithEntities text;

		[Flags] public enum Flags : uint
		{
			can_stop = 0x1,
			keep_on_stop = 0x2,
		}
	}

	/// <summary>Слой 229: inputSendMessageRichMessageDraftAction </summary>
	[TLDef(0xA937C7BE)]
	public sealed partial class InputSendMessageRichMessageDraftActionV229 : SendMessageAction
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public long random_id;
		public InputRichMessage rich_message;

		[Flags] public enum Flags : uint
		{
			can_stop = 0x1,
			keep_on_stop = 0x2,
		}
	}

	/// <summary>Слой 229: sendMessageRichMessageDraftAction </summary>
	[TLDef(0x52564893)]
	public sealed partial class SendMessageRichMessageDraftActionV229 : SendMessageAction
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public long random_id;
		public RichMessage rich_message;

		[Flags] public enum Flags : uint
		{
			can_stop = 0x1,
			keep_on_stop = 0x2,
		}
	}

	/// <summary>Слой 229: sendMessageStopDraftAction </summary>
	[TLDef(0xFBF902B0)]
	public sealed partial class SendMessageStopDraftAction : SendMessageAction
	{
		public long random_id;
	}

	/// <summary>Слой 229: textButton </summary>
	[TLDef(0xAFC79CD6)]
	public sealed partial class TextButton : RichText
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public RichText text;
		public InlineButtonType type;
		[IfFlag(0)] public RichButtonStyle style;

		[Flags] public enum Flags : uint
		{
			has_style = 0x1,
		}
	}

	/// <summary>Слой 229: pageBlockBlockquote </summary>
	[TLDef(0x66D1670B)]
	public sealed partial class PageBlockBlockquoteV229 : PageBlock
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public RichText text;
		public RichText caption;

		[Flags] public enum Flags : uint
		{
			collapsed = 0x1,
		}
	}

	/// <summary>Слой 229: pageBlockButtonRow </summary>
	[TLDef(0x6D640318)]
	public sealed partial class PageBlockButtonRow : PageBlock
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public PageButton[] buttons;

		[Flags] public enum Flags : uint
		{
			align_left = 0x1,
			align_center = 0x2,
			align_right = 0x4,
		}
	}

	/// <summary>Слой 229: pageBlockDocument </summary>
	[TLDef(0x38FA3BA3)]
	public sealed partial class PageBlockDocument : PageBlock
	{
		public long document_id;
		public PageCaption caption;
	}

	/// <summary>Слой 229: inputInvoiceStarGiftResale </summary>
	[TLDef(0xE9B0C658)]
	public sealed partial class InputInvoiceStarGiftResaleV229 : InputInvoice
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public string slug;
		public InputPeer to_id;
		[IfFlag(1)] public TextWithEntities message;

		[Flags] public enum Flags : uint
		{
			ton = 0x1,
			show_name = 0x4,
			has_message = 0x2,
		}
	}

	/// <summary>Слой 229: richButtonStyle </summary>
	[TLDef(0x03C610BD)]
	public sealed partial class RichButtonStyle : IObject
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;

		[Flags] public enum Flags : uint
		{
			bg_primary = 0x1,
			bg_danger = 0x2,
			bg_success = 0x4,
			link = 0x8,
		}
	}

	/// <summary>Слой 229: pageButton </summary>
	[TLDef(0x692A5488)]
	public sealed partial class PageButton : IObject
	{
		/// <summary>Extra bits of information, use <c>flags.HasFlag(...)</c> to test for those</summary>
		public Flags flags;
		public RichText text;
		public InlineButtonType type;
		[IfFlag(0)] public RichButtonStyle style;

		[Flags] public enum Flags : uint
		{
			has_style = 0x1,
		}
	}
}
